// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEIXRSormb5qxLADP3HkXo3er5JmPLJpI',
    appId: '1:75770336772:web:3fda30688eb0716410c751',
    messagingSenderId: '75770336772',
    projectId: 'brainqapp-9da8e',
    authDomain: 'brainqapp-9da8e.firebaseapp.com',
    storageBucket: 'brainqapp-9da8e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3f6RMValfEM3YCbBgkwSyV6TBhDChh6o',
    appId: '1:75770336772:android:bff331e3711d57e710c751',
    messagingSenderId: '75770336772',
    projectId: 'brainqapp-9da8e',
    storageBucket: 'brainqapp-9da8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsh_F1nhAD-jKNefO9cVUrp7w7PR2pb2g',
    appId: '1:75770336772:ios:6d4ca86e3a382a7110c751',
    messagingSenderId: '75770336772',
    projectId: 'brainqapp-9da8e',
    storageBucket: 'brainqapp-9da8e.firebasestorage.app',
    iosBundleId: 'com.example.brainqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsh_F1nhAD-jKNefO9cVUrp7w7PR2pb2g',
    appId: '1:75770336772:ios:6d4ca86e3a382a7110c751',
    messagingSenderId: '75770336772',
    projectId: 'brainqapp-9da8e',
    storageBucket: 'brainqapp-9da8e.firebasestorage.app',
    iosBundleId: 'com.example.brainqApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEIXRSormb5qxLADP3HkXo3er5JmPLJpI',
    appId: '1:75770336772:web:699a9b5578832d3b10c751',
    messagingSenderId: '75770336772',
    projectId: 'brainqapp-9da8e',
    authDomain: 'brainqapp-9da8e.firebaseapp.com',
    storageBucket: 'brainqapp-9da8e.firebasestorage.app',
  );
}
