"""
Django settings for brainq project.

Generated by 'django-admin startproject' using Django 5.2.7.

"""


from pathlib import Path
import os
from dotenv import load_dotenv
from celery.schedules import crontab
from logging.handlers import RotatingFileHandler


# Load .env variables
load_dotenv()


# =====================
# BASE PATHS
# =====================
BASE_DIR = Path(__file__).resolve().parent.parent


# =====================
# CORE SECURITY
# =====================
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-placeholder-secret")
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"


ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")


# =====================
# API KEYS
# =====================
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


# Firebase Service Account
firebase_path = os.getenv("FIREBASE_CREDENTIAL_PATH")
if firebase_path:
    FIREBASE_CREDENTIAL_PATH = Path(firebase_path)
else:
    # fallback for local dev if not set in .env
    FIREBASE_CREDENTIAL_PATH = BASE_DIR / "brainq" / "service_account.json"



# =====================
# APPLICATIONS
# =====================

INSTALLED_APPS = [
    'django.contrib.admin',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ai',
    'users',
    'decks',
    'achievements',
    'analytics',
    'reminders',
    'notifications.apps.NotificationsConfig'
]



# =====================
# REST FRAMEWORK
# =====================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

# =====================
# MIDDLEWARE
# =====================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.SecurityAuditMiddleware',

]


ROOT_URLCONF = 'brainq.urls'
WSGI_APPLICATION = 'brainq.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'brainq_db'),
        'USER': os.environ.get('DB_USER', 'user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =====================
# AUTH
# =====================
AUTH_USER_MODEL = 'users.CustomUser'


# =====================
# CORS
# =====================
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


# =====================
# INTERNATIONALIZATION
# =====================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# =====================
# STATIC & MEDIA
# =====================
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.CustomUser'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'no-reply@brainq.local'


# =====================
# CELERY CONFIG
# =====================

CELERY_BEAT_SCHEDULE = {
    "capture-daily-admin-metrics": {
        "task": "analytics.tasks.capture_daily_admin_metrics_task",
        "schedule": crontab(hour=0, minute=0),
    },
    "check-and-send-reminders": {
        "task": "reminders.tasks.check_and_send_reminders",
        "schedule": crontab(minute="*"),
    },
    "retry-pending-notifications": {
        "task": "notifications.tasks.retry_pending_notifications",
        "schedule": crontab(minute="*/5"),  # every 5 minutes
    },
}


# =====================
# CACHE / REDIS
# =====================

if os.getenv("REDIS_URL"):
    # Shared cache for production
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": os.getenv("REDIS_URL"),
        }
    }
else:
    # Simple in-memory cache for local devs
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }



# ==============================
# LOGGING CONFIGURATION
# ==============================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} — {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "admin_activity.log"),
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 5,             # keep last 5 logs
            "formatter": "verbose",
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": True,
        },
        "": {  # root logger
            "handlers": ["file", "console"],
            "level": "INFO",
        },
        "security": {  # security-specific logs
            "handlers": ["file", "console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

